# Pure rules config for Shadowrocket

[General]
bypass-system = true
dns-server = system,1.1.1.1,8.8.8.8
ipv6 = false
loglevel = notify
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,127.0.0.1,localhost,*.local

[Rule]
RULE-SET,https://raw.githubusercontent.com/hi-bingo/cc-rules/main/rules/reject.list,REJECT
RULE-SET,https://raw.githubusercontent.com/hi-bingo/cc-rules/main/rules/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/hi-bingo/cc-rules/main/rules/crypto.list,PROXY
RULE-SET,https://raw.githubusercontent.com/hi-bingo/cc-rules/main/rules/stocks.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Advertising/Advertising.list,REJECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Apple/Apple.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/China/China.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/OpenAI/OpenAI.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Global/Global.list,PROXY
GEOIP,CN,DIRECT
FINAL,PROXY

[URL Rewrite]
# 请开启 MITM 并在域名中加入 www.google.cn
^https?://(www.)?(g|google).cn https://www.google.com 302
